

development:
  adapter: postgresql
  database: smdbdev
  username: bweinraub
  host: localhost
  password: f@@lish!

aura-di:
  adapter: oracle_enhanced
  database: XE
  username: bonddemo
  password: bonddemo

