views:
    task_v:
    num_children_v:
    child_status_v:
functions:
    timestamp_insert:
    timestamp_update:
    set_action:
#    decimal_to_date:
triggers:
    task_create:
        functions:
            - timestamp_insert
            - timestamp_update
    task_update:
        functions:
            - timestamp_insert
            - timestamp_update
    action_create:
        functions:
            - timestamp_insert
            - timestamp_update
    action_update:
        functions:
            - timestamp_insert
            - timestamp_update
    task_context_create:
        functions:
            - timestamp_insert
            - timestamp_update
    task_context_update:
        functions:
            - timestamp_insert
            - timestamp_update
    task_command_queue_create:
        functions:
            - timestamp_insert
            - timestamp_update
    task_command_queue_update:
        functions:
            - timestamp_insert
            - timestamp_update
